消費者是否會繼續消費取決於第一次消費的單價和財力

## 1. load data

In [167]:
import numpy as np
import pandas as pd

In [168]:
# get data from csv
data_shop=pd.read_csv("Ntu_Orders.csv",low_memory=False,dtype=str)
data=pd.read_csv("NTU_1317_Member.txt",delimiter="\t",low_memory=False)

ParserError: Error tokenizing data. C error: out of memory

## 2. Preparing the data

In [162]:
data_member=data.copy()
data_member=data_member.dropna(axis=1,how="any")
del data_member["ValidFlag"]
data_member

KeyError: 'ValidFlag'

In [160]:
data_member=data_member[data_member["Recency"]!=-1]
del data_member["ShopId"]
data_member

KeyError: 'ShopId'

In [9]:
data_member["Category"]=np.zeros(len(data_member["MemberId"]))

c:\users\alixh\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
np_Quantity=np.array(data_shop["Quantity"].astype(float))
np_Price=np.array(data_shop["UnitPrice"].astype(float))
data_shop["price"]=np_Quantity*np_Price

In [22]:
dic_price=dict(data_shop.groupby("MemberId")["price"].sum())
dic_frequency=dict(data_shop["MemberId"].value_counts())

In [48]:
np.median(list(dic_price.values()))

1344.0

In [109]:
np.median(list(dic_frequency.values()))

5.0

In [136]:
temp_dic={"index":list(dic_price.keys()),"price":list(dic_price.values()),"frequency":list(dic_frequency.values())}
temp_pd=pd.DataFrame(temp_dic).set_index("index")
temp_pd

                                      frequency   price
index
00002962-4E01-4D5B-A23C-AF05A965212E       2528  6457.0
000037B9-82D7-4F41-A748-FD64AF00A535        790  1296.0
00004BE7-17B5-4DA8-A31D-673BCD22F018        663   316.0
00008557-6564-46EB-8B00-70D3DEE91FF0        649  1508.0
000248F1-4864-40B7-A987-E27884C0971C        598   597.0
000250B7-3E12-4E2F-8DFC-69ACFFCA40E9        481   570.0
00025802-0D68-43EA-B1ED-FB3C9CD849EB        476   996.0
0002954A-1267-4D54-8029-75F33C465F9B        470  1855.0
0002971E-4BEF-4F61-8B60-79E137794422        439   198.0
0002B1F3-8C4B-457F-85A9-7CD5AB62DEA3        424  1046.0
0002BC73-DD5D-4A3F-92BA-781027F0AD84        417   789.0
0002C910-4401-42AA-9B56-06D02595518C        413  1653.0
00030386-0E49-4F5D-AE62-9D3DE3B8A882        360  3668.0
00032B69-B1E5-4B44-8D7E-46917287995A        360   758.0
00036808-0160-4A0C-834B-DE351E34094D        344  1099.0
0003879A-92C5-45BD-A9ED-AEA68A6FB02B        321   398.0
00039C93-24F6-46CB-AAA6-BB9E53C4E683        308   398.0
0003A373-DA78-4C59-86B2-55EC351AAF19        303  5065.0
0003A968-FC5C-4C28-A52F-AC7D9DACF26E        298  1046.0
00040B11-6422-4086-B6DD-3C75ECB2CC13        293   757.0
00044271-09D0-449F-A7F6-976D85BC830D        287  2262.0
000445B1-4551-4CA9-8529-C953C48CE230        284   320.0
0004840A-A290-4EE8-B9A7-FE5392A1E534        281   964.0
0004CF57-178F-4EB8-93A6-726C7DB93FEF        280  1029.0
0004E2B4-55D8-4240-8955-484BC5DBEED2        275  9539.0
00054655-306F-468D-BD25-749AD9DCBF88        270  1046.0
000587ED-45FC-4191-9A6C-240A317826FF        270  1501.0
000592B9-8C9D-44D6-9FD9-E358594D5A20        268   928.0
0005BC67-2FF1-4D06-88BF-92348298E556        266   796.0
0005D4E8-F5EC-4B5C-88F0-CA1389301038        264  1736.0
...                                         ...     ...
FFF82471-5D97-425B-8738-66C3BC4A3D07          1   345.0
FFF8698D-5F39-42B3-AE12-7109F910E28D          1  1019.0
FFF94E3D-FB0C-4BEA-A076-5C444AEE4117          1  1794.0
FFF9FAD1-BD14-436B-87BC-86CF50D5AB94          1   690.0
FFFA2692-E36D-4140-B680-7340EA9EB8A3          1   828.0
FFFA2C9A-06FF-4E8D-B22E-2137C6B2174B          1  3229.0
FFFA3538-4897-43F4-A7AD-6621DEA27A33          1  1224.0
FFFAD2D6-62FD-471F-8B37-700D8598DAF1          1  5039.0
FFFAF80B-48D8-4F30-B6BA-43C2A5942749          1  2594.0
FFFB310B-C1E6-4955-A4E3-DA6F3D9E5BEA          1  1390.0
FFFBB0E0-573D-4B8D-9235-DC6A4BB26885          1  4515.0
FFFBEAB0-3B34-4109-8988-DB739B1C244E          1  1439.0
FFFC3D2B-1A90-4FE0-BC4D-ABFBB9B8EB40          1   199.0
FFFCB0A1-D36E-4DE5-A907-C9B41153E438          1   696.0
FFFCB90E-FD18-4E42-9665-582656229EA2          1  5667.0
FFFCC35C-1F56-47EA-9D96-547166C86E19          1  1866.0
FFFCDC51-5037-4F5D-8342-A0FC723D7600          1   976.0
FFFD2C83-FCAD-44FB-AC75-F115E96E10DB          1   597.0
FFFD4285-4C75-46D3-938A-6FF10B7E39D8          1  1266.0
FFFDA5CE-83C7-493E-AD9E-BA04097540A4          1   597.0
FFFDCE81-683A-4E57-AC62-E50290813C73          1   398.0
FFFE4C4F-35A7-4A51-858C-41B51E5427AE          1  1108.0
FFFE7317-2932-466D-97AE-CD2EDC6F81DA          1   946.0
FFFE8270-5055-41FA-B72A-DDE01FFC19AC          1  1413.0
FFFEFB08-3C79-4DE7-9712-51AB2ED2877F          1  1244.0
FFFF1649-4841-4049-9D8C-04B994CF18E2          1  4146.0
FFFF2C68-CF7D-4A76-B922-CFD35804DDA1          1  1122.0
FFFF4AEE-B368-43F1-92A6-FCBD291070C5          1   953.0
FFFF4FBE-3D17-4970-A968-CE47B1AC3637          1  1344.0
FFFF869E-4E27-4D37-BC69-5F298461E719          1  3056.0

[270724 rows x 2 columns]

In [147]:
temp=temp_pd[(temp_pd["frequency"]>=np.median(list(dic_frequency.values())))&(temp_pd["price"]>=np.median(list(dic_price.values())))]
category_4=zip(temp.index,[4]*len(temp))
temp=temp_pd[(temp_pd["frequency"]<np.median(list(dic_frequency.values())))&(temp_pd["price"]>=np.median(list(dic_price.values())))]
category_3=zip(temp.index,[3]*len(temp))
temp=temp_pd[(temp_pd["frequency"]>=np.median(list(dic_frequency.values())))&(temp_pd["price"]<np.median(list(dic_price.values())))]
category_2=zip(temp.index,[2]*len(temp))
temp=temp_pd[(temp_pd["frequency"]<np.median(list(dic_frequency.values())))&(temp_pd["price"]<np.median(list(dic_price.values())))]
category_1=zip(temp.index,[1]*len(temp))
category_dic=dict(list(category_1)+list(category_2)+list(category_3)+list(category_4))

In [149]:
len(data_member)

490018

In [157]:
data_member["MemberId"]=data_member["MemberId"].map(category_dic)
# data_member.fillna(0)

c:\users\alixh\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [159]:
data_member

,MemberId,Recency,Frequency,Monetary,RegisterDateTime,MinOrderDate,Category
0,NaN,251,3,4011.0,2015-09-18 19:18:48.050,2015-09-18,0.0
2,NaN,659,1,529.0,2016-03-20 02:20:35.493,2016-03-20,0.0
3,NaN,56,3,2438.0,2017-06-02 22:16:47.363,2017-06-02,0.0
4,NaN,717,1,550.0,2016-01-22 14:46:30.040,2016-01-22,0.0
5,NaN,13,3,2651.0,2015-10-01 20:13:05.657,2015-10-01,0.0
8,NaN,190,1,1174.0,2017-07-02 10:58:30.220,2017-07-02,0.0
11,NaN,165,2,2508.0,2017-04-30 20:43:30.083,2017-05-01,0.0
12,NaN,36,9,13489.0,2016-09-04 23:42:52.570,2016-09-04,0.0
15,NaN,481,1,693.0,2016-09-14 10:41:32.337,2016-09-14,0.0
16,NaN,588,1,747.0,2016-05-29 23:34:45.587,2016-05-30,0.0
18,NaN,359,1,2108.0,2017-01-14 20:37:40.677,2017-01-14,0.0
19,NaN,649,1,948.0,2016-03-30 19:51:50.397,2016-03-30,0.0
21,NaN,273,2,2774.0,2016-10-18 00:52:11.473,2016-10-18,0.0
22,NaN,467,1,783.0,2016-09-28 11:14:10.760,2016-09-28,0.0
25,NaN,180,1,1230.0,2017-07-12 21:56:51.550,2017-07-12,0.0
26,NaN,59,1,730.0,2017-11-10 21:22:57.937,2017-11-10,0.0
29,NaN,93,3,752.0,2016-07-23 21:52:24.887,2016-07-23,0.0
30,NaN,328,1,689.0,2017-02-14 20:17:36.923,2017-02-14,0.0
34,NaN,555,1,923.0,2016-07-02 13:07:07.453,2016-07-02,0.0
35,NaN,759,3,2867.0,2015-10-13 16:51:07.783,2015-10-16,0.0
36,NaN,755,1,689.0,2015-11-19 23:26:20.070,2015-12-15,0.0
39,NaN,396,3,4770.0,2015-12-10 00:30:34.497,2016-10-21,0.0
40,NaN,249,2,1498.0,2016-10-27 00:23:45.207,2017-04-05,0.0
41,NaN,597,2,1976.0,2016-04-10 10:26:17.320,2016-04-10,0.0
44,NaN,46,1,199.0,2017-11-23 02:29:41.093,2017-11-23,0.0
45,NaN,239,1,948.0,2017-05-14 13:29:17.290,2017-05-14,0.0
46,NaN,422,1,1390.0,2016-11-12 02:15:19.520,2016-11-12,0.0
49,NaN,570,1,449.0,2016-06-17 11:47:23.900,2016-06-17,0.0
50,NaN,52,1,848.0,2017-11-17 16:07:34.757,2017-11-17,0.0
51,NaN,830,1,516.0,2015-10-01 20:16:20.807,2015-10-01,0.0
...,...,...,...,...,...,...,...
815738,NaN,940,1,549.0,2015-07-14 16:38:13.857,2015-06-13,0.0
815739,NaN,377,1,2212.0,2016-12-27 00:53:20.107,2016-12-27,0.0
815740,NaN,407,1,2228.0,2016-06-22 17:16:45.913,2016-11-27,0.0
815741,NaN,866,3,1781.0,2015-07-14 16:37:35.400,2015-07-03,0.0
815742,NaN,239,1,848.0,2016-08-03 20:43:08.883,2017-05-14,0.0
815744,NaN,247,2,3445.0,2016-12-20 07:06:34.540,2016-12-20,0.0
815745,NaN,49,3,2540.0,2016-03-19 19:22:00.463,2016-03-19,0.0
815749,NaN,16,2,1745.0,2015-09-27 08:07:56.613,2016-04-17,0.0
815750,NaN,125,2,1374.0,2017-05-17 08:42:54.227,2017-05-17,0.0
815751,NaN,956,1,86.0,2015-06-11 22:07:49.033,2015-05-24,0.0
815752,NaN,486,3,1750.0,2016-06-05 23:08:28.737,2016-06-05,0.0
815753,NaN,814,2,1383.0,2015-10-12 22:10:30.320,2015-10-12,0.0
815754,NaN,110,3,3388.0,2015-09-07 02:34:48.440,2016-03-16,0.0
815755,NaN,392,2,2062.0,2016-11-19 00:08:01.587,2016-11-19,0.0
815760,NaN,316,5,3906.0,2015-11-22 17:10:29.447,2015-11-22,0.0
815761,NaN,267,2,1339.0,2015-08-01 09:50:35.027,2015-08-01,0.0
815762,NaN,824,2,1724.0,2015-07-23 18:30:36.873,2015-07-23,0.0
815763,NaN,887,1,849.0,2015-08-05 13:56:59.967,2015-08-05,0.0
815764,NaN,131,4,1169.0,2017-06-03 12:58:37.823,2017-06-03,0.0
815765,NaN,257,1,859.0,2016-08-11 23:03:56.713,2017-04-24,0.0
815766,NaN,206,1,1083.0,2017-06-16 15:57:24.407,2017-06-16,0.0
815771,NaN,10,2,2545.0,2017-01-03 00:47:44.483,2017-03-18,0.0
815772,NaN,787,1,1013.0,2015-11-13 03:09:07.757,2015-11-13,0.0
815773,NaN,268,1,199.0,2015-08-26 22:41:29.520,2016-11-09,0.0
815776,NaN,371,1,1038.0,2017-01-01 20:01:40.167,2017-01-02,0.0
815777,NaN,374,2,3224.0,2016-12-08 06:32:42.147,2016-12-08,0.0
815780,NaN,613,1,1443.0,2016-05-05 01:51:28.403,2016-05-05,0.0
815784,NaN,217,3,3243.0,2016-10-02 00:50:06.620,2016-10-02,0.0
815786,NaN,599,2,1115.0,2016-03-17 10:56:44.957,2016-03-17,0.0
815787,NaN,292,1,1166.0,2017-03-22 17:19:27.327,2017-03-22,0.0